### ISSUE TITLE
Wont launch

### ISSUE THREAD

**Issue by jark20** [tabrindle/homebridge-leviton#6]
I originally thought the problem was that it was running on Windows Server, so I tried on Windows 10 and got the same results. When I start the plugin, I get the following error;

`(node:7212) UnhandledPromiseRejectionWarning: TypeError: devices.forEach is not a function
    at HomebridgeAPI.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge-leviton\index.js:27:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by jark20** [comment]
#7 
I troubleshot the issue and discovered that My Leviton does not allow non-primary accounts to access some parts of the API, including the devices, despite admin privileges.

**Comment by Fergie2020** [comment]
Having this same issue.  I am the primary account holder for the My Leviton app so I am not sure what is causing this.  I actually tried installing and launching this and now it has completely broke the "My Leviton" app as now it won't access the internet while on my wifi at home.  If I change to cell phone data or use on a different wifi, it works fine.  Checked all firewall, ports etc and can't see to find the issue.

**Comment by mentaluproar** [comment]
I'm getting the same error.  Is this plugin dead?

**Comment by pbush25** [comment]
@tabrindle even after updating to 1.3.1 I'm still getting this issue like the others before have mentioned. This causes Homebridge to crash entirely. 

```
(node:27745) UnhandledPromiseRejectionWarning: TypeError: devices.forEach is not a function
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-leviton/index.js:27:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27745) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27745) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[16/05/2022, 09:44:54] [LevitonDecoraSmart] Socket connection opened Event { type: 'open' }
[16/05/2022, 09:44:54] TypeError: devices.forEach is not a function
    at SockJS.onmessage (/usr/lib/node_modules/homebridge-leviton/api.js:123:15)
    at SockJS.EventTarget.dispatchEvent (/usr/lib/node_modules/homebridge-leviton/node_modules/sockjs-client/lib/event/eventtarget.js:51:20)
    at /usr/lib/node_modules/homebridge-leviton/node_modules/sockjs-client/lib/main.js:281:16
    at Array.forEach (<anonymous>)
    at SockJS._transportMessage (/usr/lib/node_modules/homebridge-leviton/node_modules/sockjs-client/lib/main.js:279:17)
    at WebSocketTransport.emit (events.js:400:28)
    at Client.WebSocketTransport.ws.onmessage (/usr/lib/node_modules/homebridge-leviton/node_modules/sockjs-client/lib/transport/websocket.js:35:10)
    at Client.dispatchEvent (/usr/lib/node_modules/homebridge-leviton/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:30)
    at Client._receiveMessage (/usr/lib/node_modules/homebridge-leviton/node_modules/faye-websocket/lib/faye/websocket/api.js:154:10)
    at Client.<anonymous> (/usr/lib/node_modules/homebridge-leviton/node_modules/faye-websocket/lib/faye/websocket/api.js:36:49)
```

There is only one account on myLeviton, the one that I am using, and login via the app and web works fine.

**Comment by tabrindle** [comment]
The error suggests that there are no devices available for your residenceID. Feel free to poke around in the API, or post responses from the API, scrubbed of PII. I'll throw in a try/catch there to prevent homebridge from crashing, but you understand this is extremely hard to debug without being able to recreate the error. This plugin has worked for me for years with very few changes.

**Comment by pbush25** [comment]
@tabrindle thanks for the response. What would you recommend as the best way to poke around the API? I don't do a lot of node development, so not sure of the "right" way to debug it properly.

**Comment by pbush25** [comment]
Okay I think I see the issue. Bear with me this will be a lot of data... 

Steps with green check marks match the APIs flow on my.leviton.com. A red X is where there's a difference between what the plugin does and what the web does. 

So the plugin login & fetch flow is as such:

1. `postPersonLogin` which takes user & password and gets a token & personID back ✅
2. `getPersonResidentialPermissions` which takes the personID and token and gets the `residentialAccountId` from the response ✅
3. `getResidentialAccounts` which takes the `residentialAccountId` and the token and gets the `primaryResidenceId` from the response ✅
4. `getResidenceIotSwitches` which takes the `primaryResidenceId` and the token and for me at this point fails ❌

This is where things differ from the API on the web. 

In step 3 above, the response was of the format
```
{
    "name": "primary",
    "created": "2022-04-15T02:11:47.000Z",
    "lastUpdated": "2022-04-15T02:12:55.000Z",
    "primaryResidenceId": 000001,
    "id": 000002
}
```

Where `primaryResidenceId` is the key used by the plugin going forward to make requests, which as I said fails for me. 

Differently, the online API at this point does a fetch to `my.leviton.com/api/ResidentialAccounts/000002/residences`. Notice how this uses the `id` from the previous response, not the `primaryResidenceId`. 

This in turn returns a response of the format
```
[{
    "name": "A name",
    "some_pii_data": "data here",
    "id": 000003
}]
```

Where the object's `id` is again different from other ids we've already received back and are using. 

When the Leviton website tries to hit `my.leviton.com/api/Residences/<id>/iotswitches` it uses the `000003` id in the request, _not_ the `primaryResidenceId` that the plugin had initially cached. 

I just made this account in April of this year, so it's possible that something changed with how the user's object graph is constructed, and which ids you're supposed to use to hit that endpoint. 

I was able to confirm this via cURL. Using the `primaryResidenceId:000001` I get a response
```{"error":{"statusCode":401,"name":"Error","message":"Authorization Required"}}%```

whereas using the id in the `ResidentialAccounts/000002/residences` response, I get the expected 1 4-speed fan controller switch
```
[{"name":"Living Room Fan","power":"OFF","identify":0,"ota":false,"cloud_ota":false,"downloaded":null,"brightness":50,"manufacturer":"Leviton Manufacturing Co., Inc.","model":"DW4SF","serial":"<some_number>","version":"1.5.46; CP 1.19","minLevel":25,"maxLevel":100,"fadeOnTime":0,"fadeOffTime":0,"presetLevel":0,"dimLED":3,"statusLED":255,"loadType":0,"canSetLevel":true,"isAlexaDiscoverable":true,"includeInRoomOnOff":false,"timeZone":-300,"lat":33.94,"long":-84.39,"env":3,"programData":"AAAAAA==","buttonData":"","linkData":"","dstStart":1647154800,"dstEnd":1667714400,"dstOffset":60,"autoOffTime":0,"connected":true,"localIP":"<some.ip.address>","created":"2022-05-04T17:52:39.000Z","lastUpdated":"2022-05-16T22:11:08.000Z","random":false,"isRandomEnabled":false,"rssi":-70,"residenceId":000003,"residentialRoomId":XXXXXX,"deleted":false,"blink":0,"onTime":0,"position":null,"connectedTimestamp":"1652739065677","timeZoneName":"America/New_York","apply_ota":1,"otaStatus":0,"lang":null,"audio_cue":null,"mic_mute":null,"configuredAmazon":null,"resKey":"","allowLocalCommands":null,"mac":null,"logging":null,"resOcc":null,"customType":"ceiling-fan","iotBridgeId":null,"iotBridgeSerial":null,"btnLED":null,"motionAmbient":null,"motionAmbientThr":null,"motionDisable":null,"motionDisableTime":null,"motionGuidelight":null,"motionMode":null,"motionNightBegin":null,"motionNightEnd":null,"motionNightLevel":null,"motionNightMode":null,"motionOccupied":null,"motionSensitivity":null,"motionTest":null,"motionTimeout":null,"motionLED":null,"primary":null,"triacOff":null,"id":1169672}]
```

**Comment by pbush25** [comment]
I created the above PR in reference to this issue. I believe I have fixed it, although I'm not sure if it's exactly how you would want it done. Please feel free to let me know if you'd like changes.

**Comment by tabrindle** [comment]
ok - I've tested this out. I'll take your word for it that this fixes your issue. Definitely didn't affect operation for how my account is set up. Very strange API design ¯\_(ツ)_/¯ . 

Fixed and published as 1.5.0
